<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CoursesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('courses')->delete();
        
        \DB::table('courses')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => '1',
                'category_id' => '1',
                'subcategory_id' => '1',
                'childcategory_id' => '1',
                'language_id' => '1',
                'title' => '{"en":"WordPress Theme Development"}',
                'short_detail' => '{"en":"Have access to a code editor, free or otherwise. I suggest Coda 2, as that\'s the editor I use exclusively."}',
                'detail' => '{"en":"<p style=\\"box-sizing: border-box; margin: 0px 0px 10.5px; word-break: break-word; color: #29303b; font-family: \'sf pro text\', -apple-system, BlinkMacSystemFont, Roboto, \'segoe ui\', Helvetica, Arial, sans-serif, \'apple color emoji\', \'segoe ui emoji\', \'segoe ui symbol\'; font-size: 15px;\\"><span style=\\"box-sizing: border-box; font-weight: bold;\\">Graphic &amp; Web Designers<\\/span><\\/p>\\r\\n<p style=\\"box-sizing: border-box; margin: 0px 0px 10.5px; word-break: break-word; color: #29303b; font-family: \'sf pro text\', -apple-system, BlinkMacSystemFont, Roboto, \'segoe ui\', Helvetica, Arial, sans-serif, \'apple color emoji\', \'segoe ui emoji\', \'segoe ui symbol\'; font-size: 15px;\\">Graphic designers are extremely talented, but ask them to code their designs and they\'ll freeze up! This leaves them with no other choice but to hire a web developer. Any professional graphic designers knows web developers can be expensive.<\\/p>\\r\\n<p style=\\"box-sizing: border-box; margin: 0px 0px 10.5px; word-break: break-word; color: #29303b; font-family: \'sf pro text\', -apple-system, BlinkMacSystemFont, Roboto, \'segoe ui\', Helvetica, Arial, sans-serif, \'apple color emoji\', \'segoe ui emoji\', \'segoe ui symbol\'; font-size: 15px;\\">If you\'re a designer, learning to code your own WordPress websites can change your business entirely! Now, not only are you a great designer, but you\'re a skillful developer, too! This puts you in a position tomake an extra $1,000 &ndash; $5,000 per project.<\\/p>\\r\\n<p style=\\"box-sizing: border-box; margin: 0px 0px 10.5px; word-break: break-word; color: #29303b; font-family: \'sf pro text\', -apple-system, BlinkMacSystemFont, Roboto, \'segoe ui\', Helvetica, Arial, sans-serif, \'apple color emoji\', \'segoe ui emoji\', \'segoe ui symbol\'; font-size: 15px;\\"><span style=\\"box-sizing: border-box; font-weight: bold;\\">Quality HTML5 &amp; CSS3<\\/span><\\/p>\\r\\n<p style=\\"box-sizing: border-box; margin: 0px 0px 10.5px; word-break: break-word; color: #29303b; font-family: \'sf pro text\', -apple-system, BlinkMacSystemFont, Roboto, \'segoe ui\', Helvetica, Arial, sans-serif, \'apple color emoji\', \'segoe ui emoji\', \'segoe ui symbol\'; font-size: 15px;\\">You\'ll learn how hand-craft a stunning website with valid, semantic and beautiful HTML5 &amp; CSS3.<\\/p>\\r\\n<p style=\\"box-sizing: border-box; margin: 0px 0px 10.5px; word-break: break-word; color: #29303b; font-family: \'sf pro text\', -apple-system, BlinkMacSystemFont, Roboto, \'segoe ui\', Helvetica, Arial, sans-serif, \'apple color emoji\', \'segoe ui emoji\', \'segoe ui symbol\'; font-size: 15px;\\"><span style=\\"box-sizing: border-box; font-weight: bold;\\">Easy-to-use CMS<\\/span><\\/p>\\r\\n<p style=\\"box-sizing: border-box; margin: 0px 0px 10.5px; word-break: break-word; color: #29303b; font-family: \'sf pro text\', -apple-system, BlinkMacSystemFont, Roboto, \'segoe ui\', Helvetica, Arial, sans-serif, \'apple color emoji\', \'segoe ui emoji\', \'segoe ui symbol\'; font-size: 15px;\\">Allow your clients to easily update their websites by converting your static websites to dynamic websites, using WordPress.<\\/p>"}',
                'requirement' => '{"en":"Web Designers\\r\\n\\r\\nGraphic designers are extremely talented, but ask them to code their designs and they\'ll freeze up! This leaves them with no other choice but to hire a web developer. Any professional graphic designers knows web developers can be expensive.\\r\\n\\r\\nIf you\'re a designer, learning to code your own WordPress websites can change your business entirely! Now, not only are you a great designer, but you\'re a skillful developer, too! This puts you in a position tomake an extra $1,000 \\u2013 $5,000 per project."}',
                'price' => '1000',
                'discount_price' => '800',
                'day' => '30',
                'video' => NULL,
                'url' => 'https://www.youtube.com/watch?v=pFMgAWkrk8o',
                'featured' => '1',
                'slug' => 'wordpress-theme-development',
                'status' => '1',
                'preview_image' => 'course_15811564879.jpg',
                'video_url' => NULL,
                'preview_type' => 'url',
                'type' => '1',
                'duration' => 30,
                'duration_type' => 'm',
                'instructor_revenue' => 20,
                'created_at' => '2020-01-22 14:44:50',
                'updated_at' => '2020-08-15 11:10:23',
                'involvement_request' => 0,
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => '1',
                'category_id' => '6',
                'subcategory_id' => '15',
                'childcategory_id' => '22',
                'language_id' => '1',
                'title' => '{"en":"Ultimate Boxing Training: Professional Boxing Techniques"}',
                'short_detail' => '{"en":"Legendary Fighter Reveals The Boxing Secrets That Pummel, Destroy And Knockout Any Attacker Or Opponent Who Tries You!"}',
                'detail' => '{"en":"Legendary Fighter And World Champion Reveals New Ultimate Boxing Training Secrets To Bullet Proof Fighting Skills...Including Dirty Boxing Moves that could get you banned in the ring!\\r\\n\\r\\n- If you would like to discover how to load any strike you throw with the EXPLOSIVE POWER of a sawed-off shotgun\\u2026\\r\\n\\r\\n- EVADE your opponents with the grace of Muhammad Ali\\u2019s footwork\\u2026\\r\\n\\r\\n- And BUILD a fortress-like defense with your arms that is impenetrable by anyone no matter how big they are.."}',
                'requirement' => '{"en":"No Experience Required: If you want to learn boxing mastery skills without wasting years in a boxing gym this is hand down the best way by learning the best boxing techniques - It Doesn\\u2019t Matter If You\\u2019re Short & Under-Sized Or Have Never Been In A Real Fight Or Boxing Match, You\\u2019ll Be Shocked By How Easy It Is To Execute These Devastating Boxing Moves\\u2026"}',
                'price' => NULL,
                'discount_price' => NULL,
                'day' => NULL,
                'video' => NULL,
                'url' => 'https://www.youtube.com/watch?v=LjeJmHg_S4A',
                'featured' => '1',
                'slug' => 'ultimate-boxing-training-professional-boxing-techniques',
                'status' => '1',
                'preview_image' => '1579685773boxing.jpg',
                'video_url' => NULL,
                'preview_type' => 'url',
                'type' => '0',
                'duration' => NULL,
                'duration_type' => 'm',
                'instructor_revenue' => NULL,
                'created_at' => '2020-01-22 15:06:13',
                'updated_at' => '2020-04-23 15:33:48',
                'involvement_request' => NULL,
            ),
            2 => 
            array (
                'id' => 5,
                'user_id' => '1',
                'category_id' => '1',
                'subcategory_id' => '3',
                'childcategory_id' => '3',
                'language_id' => '1',
                'title' => '{"en":"Sketching for Fashion Design"}',
                'short_detail' => '{"en":"Learn how to sketch your fashion ideas. A step-by-step course on how professionals do it."}',
            'detail' => '{"en":"Drawing thoughts twirling in your psyche onto paper is the initial phase in building up a style portfolio and a design assortment\\/line. Having the option to share thoughts that can in the end be converted into a real piece of clothing is so significant. \\r\\n\\r\\nYour sewer and additionally design creator must have the option to take a gander at your portrayals and comprehend what you\'re imparting. The sketch will in the end become the piece of clothing along these lines should be exact and clear. \\r\\n\\r\\nYou will figure out how to make a \\"style diary\\" which will assist you with building up your own exceptional style as a style architect. Comprehending what you like (and don\'t care for) engages your structuring capacities and will bolster you in building up your one of a kind \\"voice\\". \\r\\n\\r\\nFiguring out how to draw style plans, and its act, will give you certainty and sureness; it will help your resolve, and the capacity to convey your thoughts"}',
                'requirement' => '{"en":"No course requirements or prerequisites."}',
                'price' => '700',
                'discount_price' => '400',
                'day' => NULL,
                'video' => NULL,
                'url' => 'https://www.youtube.com/watch?v=17-Tsp8Fcbw',
                'featured' => '1',
                'slug' => 'sketching-for-fashion-design',
                'status' => '1',
                'preview_image' => '157969072936.jpg',
                'video_url' => NULL,
                'preview_type' => 'url',
                'type' => '1',
                'duration' => 1,
                'duration_type' => 'm',
                'instructor_revenue' => NULL,
                'created_at' => '2020-01-22 16:28:49',
                'updated_at' => '2020-04-23 15:33:48',
                'involvement_request' => NULL,
            ),
            3 => 
            array (
                'id' => 6,
                'user_id' => '1',
                'category_id' => '5',
                'subcategory_id' => '13',
                'childcategory_id' => '13',
                'language_id' => '1',
                'title' => '{"en":"Computerized Photography for Beginners with DSLR cameras"}',
                'short_detail' => '{"en":"Figure out how to take dazzling photos by acing both the specialized and inventive sides of advanced photography."}',
                'detail' => '{"en":"Ace the most significant settings on your Canon or Nikon DSLR camera and figure out what to look like at your surroundings through new, increasingly innovative eyes, with the goal that you also can take magazine-quality photos of your companions, family, excursions, occasions and whatever else that is excellent and essential to you."}',
            'requirement' => '{"en":"- > You need a Canon or Nikon DSLR camera (the caring that has interchangable focal points) - any model will do. \\r\\n\\r\\n- > You needn\'t bother with any earlier photographic experience."}',
                'price' => '550',
                'discount_price' => '500',
                'day' => NULL,
                'video' => NULL,
                'url' => 'https://www.youtube.com/watch?v=PVdwKiTcJNs',
                'featured' => '1',
                'slug' => 'computerized-photography-for-beginners-with-dslr-cameras',
                'status' => '1',
                'preview_image' => '1579691746photography.jpg',
                'video_url' => NULL,
                'preview_type' => 'url',
                'type' => '1',
                'duration' => NULL,
                'duration_type' => 'm',
                'instructor_revenue' => NULL,
                'created_at' => '2020-01-22 16:45:47',
                'updated_at' => '2020-04-23 15:33:48',
                'involvement_request' => NULL,
            ),
            4 => 
            array (
                'id' => 10,
                'user_id' => '1',
                'category_id' => '2',
                'subcategory_id' => '6',
                'childcategory_id' => '6',
                'language_id' => '1',
                'title' => '{"en":"The Mordern JavaScript - The Complete Guide"}',
                'short_detail' => '{"en":"Modern JavaScript from the beginning - all the way up to JS expert level! THE must-have JavaScript resource in 2020."}',
                'detail' => '{"en":"It\'s an enormous course since it\'s stuffed with significant information and supportive substance. From the center nuts and bolts, over cutting edge ideas and JavaScript strengths, as far as possible up to master points like execution enhancement and testing - this course has everything. My objective was to make your go-to asset for the JavaScript language, which you can use for learning it as well as an asset you can return to and look into significant themes. \\r\\n\\r\\nThe course depends on my experience as a long haul JavaScript engineer just as an instructor with in excess of 1,000,000 understudies on Udemy just as on my YouTube channel Academind. It\'s stuffed with models, demos, ventures, assignments, tests and obviously recordings - all with the objective of giving you the most ideal method for learning JavaScript."}',
                'requirement' => '{"en":"This is the most far reaching and present day course you can discover on JavaScript - it depends on all my JavaScript information AND educating experience. It\'s both a total guide, beginning with the center essentials of the language, just as a broad reference of the JavaScript language and condition, guaranteeing that the two newcomers just as experienced JavaScript designers get a great deal out of this course!"}',
                'price' => '1000',
                'discount_price' => '800',
                'day' => NULL,
                'video' => NULL,
                'url' => 'https://www.youtube.com/watch?v=Lgxgm-T9cgA&list=PL0b6OzIxLPbx-BZTaWu_AF7hsKo_Fvsnf',
                'featured' => '0',
                'slug' => 'the-mordern-javascript-the-complete-guide',
                'status' => '1',
                'preview_image' => '157976014948.jpg',
                'video_url' => NULL,
                'preview_type' => 'url',
                'type' => '1',
                'duration' => NULL,
                'duration_type' => 'm',
                'instructor_revenue' => NULL,
                'created_at' => '2020-01-23 11:45:01',
                'updated_at' => '2020-04-23 15:33:48',
                'involvement_request' => NULL,
            ),
            5 => 
            array (
                'id' => 12,
                'user_id' => '1',
                'category_id' => '2',
                'subcategory_id' => '7',
                'childcategory_id' => '8',
                'language_id' => '1',
                'title' => '{"en":"SQL: Learn SQL for data analysis"}',
                'short_detail' => '{"en":"Step by Step SQL with MySQL Database for Beginners, Non-Techs, newbs - Quick way to learn SQL using MySQL Database"}',
            'detail' => '{"en":"This is a novice level course. On the off chance that you have earlier information on SQL than this course may fill in as boost yet won\'t show you many propelled ideas. \\r\\n\\r\\nWhy you ought to gain from me? \\r\\n\\r\\nI have been in Digital Marketing and Analytics for more than 15 years. I have prepared individuals from various foundations and have changed over them into high performing Digital Marketers and Analysts. I comprehend both the innovation and promoting side of business. I have managed numerous investigation advancements path before Google Tag chief existed and know the inward working of Digital Analytics. \\r\\n\\r\\nLikewise, I have created different course and showed understudies from everywhere throughout the world. I am online educator for University of British Columbia (Canada), University of Washington (USA), Bellevue College (USA) and Digital Analytics Association."}',
                'requirement' => '{"en":"You needn\'t bother with long stretches of talks to learn SQL and MySQL, that is actually how I moved toward this course. I blended the data so it is snappy and straightforward. \\r\\n\\r\\nIn this course I have rearranged the procedure without getting into all the perplexing specialized stand up so anyone can learn SQL. This course is intended to make each progression straightforward. I utilized similar techniques that I use to show business experts and advertising investigators in my very own gathering."}',
                'price' => '1000',
                'discount_price' => '500',
                'day' => NULL,
                'video' => NULL,
                'url' => 'https://www.youtube.com/watch?v=HXV3zeQKqGY',
                'featured' => '1',
                'slug' => 'sql-learn-sql-for-data-analysis',
                'status' => '1',
                'preview_image' => '157976112152.jpg',
                'video_url' => NULL,
                'preview_type' => 'url',
                'type' => '1',
                'duration' => NULL,
                'duration_type' => 'm',
                'instructor_revenue' => NULL,
                'created_at' => '2020-01-23 12:02:01',
                'updated_at' => '2020-04-23 15:33:48',
                'involvement_request' => NULL,
            ),
            6 => 
            array (
                'id' => 14,
                'user_id' => '1',
                'category_id' => '3',
                'subcategory_id' => '8',
                'childcategory_id' => '11',
                'language_id' => '1',
                'title' => '{"en":"Music Production with Mixing & Mastering"}',
                'short_detail' => '{"en":"Learning the tricks and techniques to mixing and mastering your songs"}',
                'detail' => '{"en":"On the off chance that you need to improve your melody blends in Studio One, this is the ideal course for you! \\r\\n\\r\\nFigure out how to Mix and Master them inside Studio One \\r\\n\\r\\nThis is a finished course showing you how to utilize every one of the apparatuses and capabilities in Studio One to give you an incredible blended, aced and settled tune\\/s \\r\\n\\r\\nWith simple to-follow instructional exercises and a true case of a melody from beginning to end, you\'ll appreciate learning while at the same time making a move."}',
                'requirement' => '{"en":"Focused on clients that need to show signs of improvement at their blending and acing inside Studio One \\r\\n\\r\\nMusic Composers, Producers working with Studio who need to realize the instruments better \\r\\n\\r\\nClients who need to take their Studio one Songs further and clean them up so they contrast and other business discharges."}',
                'price' => '1000',
                'discount_price' => '900',
                'day' => NULL,
                'video' => NULL,
                'url' => 'https://www.youtube.com/watch?v=ab_TBVZewoQ',
                'featured' => '1',
                'slug' => 'music-production-with-mixing-mastering',
                'status' => '1',
                'preview_image' => '157976172453.jpg',
                'video_url' => NULL,
                'preview_type' => 'url',
                'type' => '1',
                'duration' => NULL,
                'duration_type' => 'm',
                'instructor_revenue' => NULL,
                'created_at' => '2020-01-23 12:12:04',
                'updated_at' => '2020-04-23 15:33:48',
                'involvement_request' => NULL,
            ),
            7 => 
            array (
                'id' => 17,
                'user_id' => '1',
                'category_id' => '4',
                'subcategory_id' => '10',
                'childcategory_id' => '1',
                'language_id' => '1',
                'title' => '{"en":"HOW TO PAINT- Portrait Painting From Photograph"}',
                'short_detail' => '{"en":"Learn How to Draw and Paint Colorful and Vibrant Portrait Paintings in Watercolor"}',
                'detail' => '{"en":"Through showings and talks I will rearrange the procedure so even somebody who\'s never painted can get it. We\'ll go over some essential plan ideas,and then get right to the Fun part, Painting Abstract Art. \\r\\n\\r\\nAnybody needing to paint even only one Abstract Painting should profit by this Course, and for those needing to profit, I\'ll show you various approaches to sell your compositions. \\r\\n\\r\\nPresently please Watch the PREVIEWS Below, and Check out what different Students Say \\r\\n\\r\\nDiminish \\"I truly making the most of Andy\'s casual style of educating in this course. Extraordinary tips of how to set aside on cash on paint and instruments were convenient and adored tuning in to his manner of thinking while at the same time watching him paint.\\""}',
                'requirement' => '{"en":"This is such an extraordinary course for an amateur or somebody needing to return to painting to energize their imaginative juices. As an apprentice this is exactly what I expected to make me go. purchased my provisions presently to make workmanship."}',
                'price' => '1200',
                'discount_price' => '700',
                'day' => NULL,
                'video' => NULL,
                'url' => 'https://www.youtube.com/watch?v=Q65omT5Zo54',
                'featured' => '1',
                'slug' => 'how-to-paint-portrait-painting-from-photograph',
                'status' => '1',
                'preview_image' => '157976358156.jpg',
                'video_url' => NULL,
                'preview_type' => 'url',
                'type' => '0',
                'duration' => NULL,
                'duration_type' => 'm',
                'instructor_revenue' => NULL,
                'created_at' => '2020-01-23 12:43:01',
                'updated_at' => '2020-04-23 15:33:48',
                'involvement_request' => NULL,
            ),
            8 => 
            array (
                'id' => 18,
                'user_id' => '1',
                'category_id' => '4',
                'subcategory_id' => '11',
                'childcategory_id' => '16',
                'language_id' => '1',
                'title' => '{"en":"Hair styling- The Ultimate Hair Course"}',
                'short_detail' => '{"en":"You won\'t visit a hairdresser again! Cut, dye  and style your hair yourself at home."}',
                'detail' => '{"en":"Voluminous, solid twists without backcombing\\/prodding or pleating, even the biggest length. \\r\\n\\r\\nIs it accurate to say that you are longing for radiant twists and a huge volume? However, your customers fear prodding or pleating... \\r\\n\\r\\nI know it all about twists. What\'s more, in this exercise I sincerely share every one of the privileged insights. You even didn\'t feel that everything is so straightforward. Anybody with any degree of preparing can ace the abilities. \\r\\n\\r\\nI will tell about hair arrangement. This is the most significant advance. Skirting this specific advance, you are committing a gross error."}',
                'requirement' => '{"en":"Next, how about we talk about the apparatuses and the correct temperature to make solid twists. \\r\\n\\r\\nWe are completing with a hair obsession. A large number of brands and varnishes. Be that as it may, many don\'t hold hair and make dust. Subsequently, the styling is messy."}',
                'price' => '1200',
                'discount_price' => '500',
                'day' => NULL,
                'video' => NULL,
                'url' => 'https://www.youtube.com/watch?v=-poUN5MNb_U',
                'featured' => '0',
                'slug' => 'hair-styling-the-ultimate-hair-course',
                'status' => '1',
                'preview_image' => '157976385857.jpg',
                'video_url' => NULL,
                'preview_type' => 'url',
                'type' => '1',
                'duration' => NULL,
                'duration_type' => 'm',
                'instructor_revenue' => NULL,
                'created_at' => '2020-01-23 12:47:38',
                'updated_at' => '2020-04-23 15:33:48',
                'involvement_request' => NULL,
            ),
            9 => 
            array (
                'id' => 20,
                'user_id' => '1',
                'category_id' => '4',
                'subcategory_id' => '12',
                'childcategory_id' => '19',
                'language_id' => '1',
                'title' => '{"en":"Travel Hacking -Smart & Fun Travel"}',
                'short_detail' => '{"en":"60+ World Travel Tips: Cheap Travel. Fear of Flying. Travel Motivation & Safety. Negotiation. Social Success Abroad."}',
                'detail' => '{"en":"At that point the course will cover how to discover nearby gatherings to hang out, neighborhood occasions to go to anyplace on the planet, how to meet different explorers simply like you, how to go to astonishing occasions that will transform yourself at a reasonable cost anyplace on the planet. Figure out how to get 100% confided in nearby astounding independently directed visits that you can do without anyone else in any piece of the world, stunning ventures applications to use to grow your voyaging experience, how to discover explicit concentrated data on neighborhood mystery occasions, and how to discover astonishing free nature areas around the globe to unwind in. \\r\\n\\r\\nWe at that point proceed onward to the tips on the most proficient method to make durable fellowships with different voyagers. Likewise, something that many individuals don\'t consider is dating while at the same time voyaging. Well here in this course, we will cover the most ideal approaches to date while voyaging. You will find the probably the best dating applications. We need you can concentrate on movement first and dating second."}',
                'requirement' => '{"en":"Find the approaches to kill dejection and dread of voyaging and plan your movement for an astonishing travel encounters at a reasonable expense. The course will tell you the best way to deal with your cash and deal with your consumption effectively so you are never stuck anyplace with no cash during movement."}',
                'price' => '1000',
                'discount_price' => '500',
                'day' => NULL,
                'video' => NULL,
                'url' => 'https://www.youtube.com/watch?v=_eMAXOp2PvA',
                'featured' => '1',
                'slug' => 'travel-hacking-smart-fun-travel',
                'status' => '1',
                'preview_image' => '157976457360.jpg',
                'video_url' => NULL,
                'preview_type' => 'url',
                'type' => '1',
                'duration' => NULL,
                'duration_type' => 'm',
                'instructor_revenue' => NULL,
                'created_at' => '2020-01-23 12:59:33',
                'updated_at' => '2020-04-23 15:33:48',
                'involvement_request' => NULL,
            ),
        ));
        
        
    }
}