<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CourseClassesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('course_classes')->delete();
        
        \DB::table('course_classes')->insert(array (
            0 => 
            array (
                'id' => 28,
                'course_id' => '5',
                'coursechapter_id' => '15',
                'title' => '{"en":"Steps in Fashion Illustration"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=17-Tsp8Fcbw',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '30',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-22 16:44:14',
                'updated_at' => '2020-01-22 16:44:14',
                'user_id' => NULL,
                'file' => NULL,
            ),
            1 => 
            array (
                'id' => 29,
                'course_id' => '5',
                'coursechapter_id' => '16',
                'title' => '{"en":"How to draw a dress design - Dresses Drawing"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=nXKFBA0xeYQ',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '10',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-22 16:45:40',
                'updated_at' => '2020-01-22 16:45:40',
                'user_id' => NULL,
                'file' => NULL,
            ),
            2 => 
            array (
                'id' => 30,
                'course_id' => '5',
                'coursechapter_id' => '17',
                'title' => '{"en":"Tips to draw better a fashion sketch"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=iW3FuhxnAPo',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '4',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-22 16:49:26',
                'updated_at' => '2020-01-22 17:32:00',
                'user_id' => NULL,
                'file' => NULL,
            ),
            3 => 
            array (
                'id' => 31,
                'course_id' => '6',
                'coursechapter_id' => '19',
                'title' => '{"en":"Is my camera good enough?"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=Hcb8Ftm1Lac',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '13.25',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-22 16:57:28',
                'updated_at' => '2020-01-22 16:57:28',
                'user_id' => NULL,
                'file' => NULL,
            ),
            4 => 
            array (
                'id' => 32,
                'course_id' => '6',
                'coursechapter_id' => '19',
                'title' => '{"en":"Choosing the right lens"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=zjKNZ1ydE9I',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '9.22',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-22 16:58:30',
                'updated_at' => '2020-01-22 16:58:30',
                'user_id' => NULL,
                'file' => NULL,
            ),
            5 => 
            array (
                'id' => 33,
                'course_id' => '5',
                'coursechapter_id' => '18',
                'title' => '{"en":"FASHION ILLUSTRATION TUTORIAL"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'youtube.com/watch?v=_uUNMHFSsBk',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '7',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-22 16:59:33',
                'updated_at' => '2020-01-22 16:59:33',
                'user_id' => NULL,
                'file' => NULL,
            ),
            6 => 
            array (
                'id' => 34,
                'course_id' => '6',
                'coursechapter_id' => '19',
                'title' => '{"en":"Bean Bag for Wildlife Photography"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=R8vJZvvuTzo',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '1:15',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-22 17:02:58',
                'updated_at' => '2020-01-22 17:02:58',
                'user_id' => NULL,
                'file' => NULL,
            ),
            7 => 
            array (
                'id' => 35,
                'course_id' => '6',
                'coursechapter_id' => '20',
                'title' => '{"en":"Introduction"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=P427Zr3gUV4',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '17:01',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-22 17:04:17',
                'updated_at' => '2020-01-22 17:04:17',
                'user_id' => NULL,
                'file' => NULL,
            ),
            8 => 
            array (
                'id' => 36,
                'course_id' => '5',
                'coursechapter_id' => '17',
                'title' => '{"en":"Fashion Design"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=Z1cJzaB_COI',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '4:35',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-22 17:04:34',
                'updated_at' => '2020-01-22 17:04:34',
                'user_id' => NULL,
                'file' => NULL,
            ),
            9 => 
            array (
                'id' => 37,
                'course_id' => '6',
                'coursechapter_id' => '19',
                'title' => '{"en":"Right shooting mode"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=j-I8R8pn7uY',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '4:39',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-22 17:05:24',
                'updated_at' => '2020-01-22 17:05:24',
                'user_id' => NULL,
                'file' => NULL,
            ),
            10 => 
            array (
                'id' => 38,
                'course_id' => '6',
                'coursechapter_id' => '19',
                'title' => '{"en":"Drive mode"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=wD1DBdZIb4M',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '4:26',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-22 17:06:54',
                'updated_at' => '2020-01-22 17:06:54',
                'user_id' => NULL,
                'file' => NULL,
            ),
            11 => 
            array (
                'id' => 39,
                'course_id' => '6',
                'coursechapter_id' => '21',
                'title' => '{"en":"Front light"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=VNdQ3dZ1FXY',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '1:33',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-22 17:09:04',
                'updated_at' => '2020-01-22 17:09:04',
                'user_id' => NULL,
                'file' => NULL,
            ),
            12 => 
            array (
                'id' => 40,
                'course_id' => '6',
                'coursechapter_id' => '19',
                'title' => '{"en":"Diffused light"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=N2y-XA_aAYE',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '5:52',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-22 17:10:18',
                'updated_at' => '2020-01-22 17:10:18',
                'user_id' => NULL,
                'file' => NULL,
            ),
            13 => 
            array (
                'id' => 41,
                'course_id' => '6',
                'coursechapter_id' => '22',
                'title' => '{"en":"Camera orientation"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=hRZ5V5cdBl4',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '1:59',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-22 17:12:34',
                'updated_at' => '2020-01-22 17:12:34',
                'user_id' => NULL,
                'file' => NULL,
            ),
            14 => 
            array (
                'id' => 42,
                'course_id' => '6',
                'coursechapter_id' => '22',
                'title' => '{"en":"leading lines"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=iYwGpMfeV68',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '6:23',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-22 17:14:15',
                'updated_at' => '2020-01-22 17:14:15',
                'user_id' => NULL,
                'file' => NULL,
            ),
            15 => 
            array (
                'id' => 43,
                'course_id' => '6',
                'coursechapter_id' => '23',
                'title' => '{"en":"Look for reflections"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=Jayb8BzPoOs',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '12:15',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-22 17:17:04',
                'updated_at' => '2020-01-22 17:17:04',
                'user_id' => NULL,
                'file' => NULL,
            ),
            16 => 
            array (
                'id' => 55,
                'course_id' => '1',
                'coursechapter_id' => '33',
                'title' => '{"en":"How to Install WordPress"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=pFMgAWkrk8o',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '11:36',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => 'url',
                'date_time' => NULL,
                'detail' => '<p style="box-sizing: border-box; margin: 0px; word-break: break-word; color: #686f7a; font-family: \'sf pro text\', -apple-system, BlinkMacSystemFont, Roboto, \'segoe ui\', Helvetica, Arial, sans-serif, \'apple color emoji\', \'segoe ui emoji\', \'segoe ui symbol\'; font-size: 13px; letter-spacing: 0.3px; background-color: #ffffff;">In this lecture, we\'re going to take a look at the final WordPress website we\'re going to have built by the end of the course. You\'ll see:</p>
<ol style="box-sizing: border-box; margin-top: 0px; margin-bottom: 10.5px; padding-left: 35px; color: #686f7a; font-family: \'sf pro text\', -apple-system, BlinkMacSystemFont, Roboto, \'segoe ui\', Helvetica, Arial, sans-serif, \'apple color emoji\', \'segoe ui emoji\', \'segoe ui symbol\'; font-size: 13px; letter-spacing: 0.3px; background-color: #ffffff;">
<li style="box-sizing: border-box;"><span style="box-sizing: border-box;">The beautiful, custom home page</span></li>
<li style="box-sizing: border-box;"><span style="box-sizing: border-box;">Dynamic testimonials</span></li>
<li style="box-sizing: border-box;"><span style="box-sizing: border-box;">How to edit the logo in the WordPress customizer</span></li>
<li style="box-sizing: border-box;">The custom blog page</li>
<li style="box-sizing: border-box;">How to add dynamic resources</li>
<li style="box-sizing: border-box;">Contact page</li>
<li style="box-sizing: border-box;">The WordPress admin panel</li>
</ol>',
                'position' => 2,
                'aws_upload' => NULL,
                'created_at' => '2020-01-23 21:13:05',
                'updated_at' => '2020-06-21 01:31:05',
                'user_id' => NULL,
                'file' => NULL,
            ),
            17 => 
            array (
                'id' => 56,
                'course_id' => '1',
                'coursechapter_id' => '34',
                'title' => '{"en":"WordPress Page Templates"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=ynA8_5jAc1s&list=PLpcSpRrAaOaqMA4RdhSnnNcaqOVpX7qi5&index=6&t=0s',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '12:36',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => 'url',
                'date_time' => NULL,
                'detail' => '<p><span style="box-sizing: border-box; color: #686f7a; font-family: \'sf pro text\', -apple-system, BlinkMacSystemFont, Roboto, \'segoe ui\', Helvetica, Arial, sans-serif, \'apple color emoji\', \'segoe ui emoji\', \'segoe ui symbol\'; font-size: 13px; letter-spacing: 0.3px; background-color: #ffffff;">In this lecture we\'re going to add some resources using Custom Post Types UI, then code our resources template to dynamically display each individual</span><span style="color: #686f7a; font-family: \'sf pro text\', -apple-system, BlinkMacSystemFont, Roboto, \'segoe ui\', Helvetica, Arial, sans-serif, \'apple color emoji\', \'segoe ui emoji\', \'segoe ui symbol\'; font-size: 13px; letter-spacing: 0.3px; background-color: #ffffff;">&nbsp;resource.</span></p>',
                'position' => 3,
                'aws_upload' => NULL,
                'created_at' => '2020-01-23 21:14:28',
                'updated_at' => '2020-06-21 01:28:00',
                'user_id' => NULL,
                'file' => NULL,
            ),
            18 => 
            array (
                'id' => 57,
                'course_id' => '1',
                'coursechapter_id' => '34',
                'title' => '{"en":"WordPress Navigation Menus"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=AShql_Ap1Yo&list=PLpcSpRrAaOaqMA4RdhSnnNcaqOVpX7qi5&index=5&t=0s',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '16:45',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => 4,
                'aws_upload' => NULL,
                'created_at' => '2020-01-23 21:15:18',
                'updated_at' => '2020-01-23 21:15:18',
                'user_id' => NULL,
                'file' => NULL,
            ),
            19 => 
            array (
                'id' => 58,
                'course_id' => '1',
                'coursechapter_id' => '35',
                'title' => '{"en":"WordPress Page Templates"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=snFzbPm_RUE&list=PLpcSpRrAaOaqMA4RdhSnnNcaqOVpX7qi5&index=3&t=0s',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '12',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => 5,
                'aws_upload' => NULL,
                'created_at' => '2020-01-23 21:16:17',
                'updated_at' => '2020-01-23 21:16:17',
                'user_id' => NULL,
                'file' => NULL,
            ),
            20 => 
            array (
                'id' => 59,
                'course_id' => '1',
                'coursechapter_id' => '33',
                'title' => '{"en":"Wordpress Theme Developement"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=ANWmIj2lpJI&list=PLahZD2By8BGrFMNBqR6G_f1k6iNKfY3eW',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '6:19',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => 'url',
                'date_time' => NULL,
                'detail' => '<p><span style="color: #686f7a; font-family: \'sf pro text\', -apple-system, BlinkMacSystemFont, Roboto, \'segoe ui\', Helvetica, Arial, sans-serif, \'apple color emoji\', \'segoe ui emoji\', \'segoe ui symbol\'; font-size: 13px; letter-spacing: 0.3px; background-color: #ffffff;">Bootstrap is the most popular front-end framework on the web today.&nbsp;</span><span style="box-sizing: border-box; color: #686f7a; font-family: \'sf pro text\', -apple-system, BlinkMacSystemFont, Roboto, \'segoe ui\', Helvetica, Arial, sans-serif, \'apple color emoji\', \'segoe ui emoji\', \'segoe ui symbol\'; font-size: 13px; letter-spacing: 0.3px; background-color: #ffffff;">In this lecture, I talk about how</span><span style="box-sizing: border-box; color: #686f7a; font-family: \'sf pro text\', -apple-system, BlinkMacSystemFont, Roboto, \'segoe ui\', Helvetica, Arial, sans-serif, \'apple color emoji\', \'segoe ui emoji\', \'segoe ui symbol\'; font-size: 13px; letter-spacing: 0.3px; background-color: #ffffff;">&nbsp;learning to properly use Bootstrap can save yourself hundreds of hours, and increase your work output by up to 100%.</span></p>',
                'position' => 6,
                'aws_upload' => NULL,
                'created_at' => '2020-01-23 21:17:50',
                'updated_at' => '2020-06-21 01:31:38',
                'user_id' => NULL,
                'file' => NULL,
            ),
            21 => 
            array (
                'id' => 64,
                'course_id' => '10',
                'coursechapter_id' => '37',
                'title' => '{"en":"Advanced JavaScript - Module 01"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=UqWN8LXUldc&list=PLvZkOAgBYrsSZiL0L7T-CBGdiBUaHok4x&index=2&t=0s',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '0:32',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-23 23:16:52',
                'updated_at' => '2020-01-23 23:16:52',
                'user_id' => NULL,
                'file' => NULL,
            ),
            22 => 
            array (
                'id' => 65,
                'course_id' => '10',
                'coursechapter_id' => '38',
                'title' => '{"en":"Various types of array declarations and initializations"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=jTxK6scDIUU&list=PLvZkOAgBYrsSZiL0L7T-CBGdiBUaHok4x&index=4&t=0s',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '5:45',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-23 23:17:53',
                'updated_at' => '2020-01-23 23:17:53',
                'user_id' => NULL,
                'file' => NULL,
            ),
            23 => 
            array (
                'id' => 66,
                'course_id' => '10',
                'coursechapter_id' => '39',
                'title' => '{"en":"Functions, Anonymous, FE, IIFE, Callbacks"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=VsvYUp61m1o&list=PLvZkOAgBYrsSZiL0L7T-CBGdiBUaHok4x&index=9&t=0s',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '0:54',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-23 23:56:11',
                'updated_at' => '2020-01-23 23:56:11',
                'user_id' => NULL,
                'file' => NULL,
            ),
            24 => 
            array (
                'id' => 67,
                'course_id' => '10',
                'coursechapter_id' => '48',
                'title' => '{"en":"Nesting objects"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=YriClnrLK_s&list=PLvZkOAgBYrsSZiL0L7T-CBGdiBUaHok4x&index=25',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '6:45',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-23 23:57:04',
                'updated_at' => '2020-01-23 23:57:04',
                'user_id' => NULL,
                'file' => NULL,
            ),
            25 => 
            array (
                'id' => 68,
                'course_id' => '10',
                'coursechapter_id' => '48',
                'title' => '{"en":"Dangers of using Array.length"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=TCFaey2v6JU&list=PLvZkOAgBYrsSZiL0L7T-CBGdiBUaHok4x&index=6',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '11:35',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-23 23:57:46',
                'updated_at' => '2020-01-23 23:57:46',
                'user_id' => NULL,
                'file' => NULL,
            ),
            26 => 
            array (
                'id' => 73,
                'course_id' => '12',
                'coursechapter_id' => '49',
                'title' => '{"en":"Connecting to SQL Server"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=ZNObiptSMSI&list=PL08903FB7ACA1C2FB&index=2&t=0s',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '6',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-24 00:05:24',
                'updated_at' => '2020-01-24 00:06:42',
                'user_id' => NULL,
                'file' => NULL,
            ),
            27 => 
            array (
                'id' => 74,
                'course_id' => '12',
                'coursechapter_id' => '50',
                'title' => '{"en":"Creating altering and dropping a database"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => '6:55',
                'url' => 'https://www.youtube.com/watch?v=TuxuHHacIWU&list=PL08903FB7ACA1C2FB&index=3&t=0s',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '8',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-24 00:06:00',
                'updated_at' => '2020-01-24 00:06:00',
                'user_id' => NULL,
                'file' => NULL,
            ),
            28 => 
            array (
                'id' => 75,
                'course_id' => '12',
                'coursechapter_id' => '49',
                'title' => '{"en":"Creating and working with tables"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=JLeaM8pK8dE&list=PL08903FB7ACA1C2FB&index=4&t=0s',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '12',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-24 00:06:23',
                'updated_at' => '2020-01-24 00:06:34',
                'user_id' => NULL,
                'file' => NULL,
            ),
            29 => 
            array (
                'id' => 80,
                'course_id' => '14',
                'coursechapter_id' => '56',
                'title' => '{"en":"Music Production Tutorials"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/user/musicprotutorials',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '3',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-24 00:15:09',
                'updated_at' => '2020-01-24 00:15:09',
                'user_id' => NULL,
                'file' => NULL,
            ),
            30 => 
            array (
                'id' => 81,
                'course_id' => '14',
                'coursechapter_id' => '56',
                'title' => '{"en":"Music Production Tutorials"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?time_continue=61&v=8ok0oDhmibg',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '9',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-24 00:15:15',
                'updated_at' => '2020-01-24 00:15:15',
                'user_id' => NULL,
                'file' => NULL,
            ),
            31 => 
            array (
                'id' => 82,
                'course_id' => '14',
                'coursechapter_id' => '56',
                'title' => '{"en":"Music Production Tutorials"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?time_continue=61&v=8ok0oDhmibg',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '8',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-24 00:15:21',
                'updated_at' => '2020-01-24 00:15:21',
                'user_id' => NULL,
                'file' => NULL,
            ),
            32 => 
            array (
                'id' => 83,
                'course_id' => '14',
                'coursechapter_id' => '56',
                'title' => '{"en":"Music Production Tutorials"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?time_continue=61&v=8ok0oDhmibg',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '6',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-24 00:15:26',
                'updated_at' => '2020-01-24 00:15:26',
                'user_id' => NULL,
                'file' => NULL,
            ),
            33 => 
            array (
                'id' => 92,
                'course_id' => '17',
                'coursechapter_id' => '65',
                'title' => '{"en":"Tutorial 1"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=Hb1bALhfnXQ',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '9',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-24 00:25:24',
                'updated_at' => '2020-01-24 00:25:24',
                'user_id' => NULL,
                'file' => NULL,
            ),
            34 => 
            array (
                'id' => 93,
                'course_id' => '17',
                'coursechapter_id' => '65',
                'title' => '{"en":"Tutorial 2"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=my7Fqxf2ZxU',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '4',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-24 00:25:31',
                'updated_at' => '2020-01-24 00:26:04',
                'user_id' => NULL,
                'file' => NULL,
            ),
            35 => 
            array (
                'id' => 94,
                'course_id' => '17',
                'coursechapter_id' => '65',
                'title' => '{"en":"Tutorial 3"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=r9LskpW5P3Y',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '3',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-24 00:25:37',
                'updated_at' => '2020-01-24 00:25:56',
                'user_id' => NULL,
                'file' => NULL,
            ),
            36 => 
            array (
                'id' => 95,
                'course_id' => '17',
                'coursechapter_id' => '65',
                'title' => '{"en":"Tutorial 4"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=CNwG8C9bXhE',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '10:45',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-24 00:25:44',
                'updated_at' => '2020-01-24 00:25:44',
                'user_id' => NULL,
                'file' => NULL,
            ),
            37 => 
            array (
                'id' => 96,
                'course_id' => '18',
                'coursechapter_id' => '68',
                'title' => '{"en":"Tutorial 1"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=vsVTUXu-psA',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '5',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-24 00:33:37',
                'updated_at' => '2020-01-24 00:33:37',
                'user_id' => NULL,
                'file' => NULL,
            ),
            38 => 
            array (
                'id' => 97,
                'course_id' => '18',
                'coursechapter_id' => '70',
                'title' => '{"en":"Tutorial 2"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=25fQ5QB70HE',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '6',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-24 00:33:52',
                'updated_at' => '2020-01-24 00:38:05',
                'user_id' => NULL,
                'file' => NULL,
            ),
            39 => 
            array (
                'id' => 98,
                'course_id' => '18',
                'coursechapter_id' => '69',
                'title' => '{"en":"Tutorial 3"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=nlk77yWZRiM',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '4',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-24 00:33:53',
                'updated_at' => '2020-01-24 00:38:18',
                'user_id' => NULL,
                'file' => NULL,
            ),
            40 => 
            array (
                'id' => 99,
                'course_id' => '18',
                'coursechapter_id' => '71',
                'title' => '{"en":"Tutorial 4"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=IQ9lyPUXOPg',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '10',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-24 00:34:16',
                'updated_at' => '2020-01-24 00:38:27',
                'user_id' => NULL,
                'file' => NULL,
            ),
            41 => 
            array (
                'id' => 102,
                'course_id' => '20',
                'coursechapter_id' => '74',
                'title' => '{"en":"Tutorial 1"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=7Eh4ZQEtTM0',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '7',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-24 00:41:20',
                'updated_at' => '2020-01-24 00:41:20',
                'user_id' => NULL,
                'file' => NULL,
            ),
            42 => 
            array (
                'id' => 103,
                'course_id' => '20',
                'coursechapter_id' => '75',
                'title' => '{"en":"Tutorial 2"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=dy8709aoU2E',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '5',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-24 00:41:29',
                'updated_at' => '2020-01-24 00:41:29',
                'user_id' => NULL,
                'file' => NULL,
            ),
            43 => 
            array (
                'id' => 104,
                'course_id' => '20',
                'coursechapter_id' => '76',
                'title' => '{"en":"Tutorial 3"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://drive.google.com/drive/my-drive',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '7',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => NULL,
                'aws_upload' => NULL,
                'created_at' => '2020-01-24 00:41:43',
                'updated_at' => '2020-02-05 18:01:07',
                'user_id' => NULL,
                'file' => NULL,
            ),
            44 => 
            array (
                'id' => 105,
                'course_id' => '1',
                'coursechapter_id' => '36',
                'title' => '{"en":"Image"}',
                'image' => '1581672352orlova-maria-x9WIHLvqMA0-unsplash.jpg',
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => '12',
                'url' => NULL,
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => NULL,
                'status' => '1',
                'featured' => '1',
                'type' => 'image',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => 7,
                'aws_upload' => NULL,
                'created_at' => '2020-02-14 14:55:52',
                'updated_at' => '2020-02-14 14:55:52',
                'user_id' => NULL,
                'file' => NULL,
            ),
            45 => 
            array (
                'id' => 106,
                'course_id' => '1',
                'coursechapter_id' => '36',
                'title' => '{"en":"video upload"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => NULL,
                'iframe_url' => NULL,
                'video' => 'video_course_1582697616.webm',
                'duration' => '12',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => NULL,
                'date_time' => NULL,
                'detail' => NULL,
                'position' => 8,
                'aws_upload' => NULL,
                'created_at' => '2020-02-26 10:47:57',
                'updated_at' => '2020-02-26 11:43:36',
                'user_id' => NULL,
                'file' => NULL,
            ),
            46 => 
            array (
                'id' => 107,
                'course_id' => '1',
                'coursechapter_id' => '33',
                'title' => '{"en":"Devlopment"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=8AZ8GqW5iak',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => '10',
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => 'https://www.youtube.com/watch?v=snFzbPm_RUE&list=PLpcSpRrAaOaqMA4RdhSnnNcaqOVpX7qi5&index=3&t=0s',
                'preview_type' => 'url',
                'date_time' => NULL,
                'detail' => '<p><span style="color: #686f7a; font-family: \'sf pro text\', -apple-system, BlinkMacSystemFont, Roboto, \'segoe ui\', Helvetica, Arial, sans-serif, \'apple color emoji\', \'segoe ui emoji\', \'segoe ui symbol\'; font-size: 13px; letter-spacing: 0.3px; background-color: #ffffff;">In this lecture, we\'ll clean up and customize the stylesheet that is provided with the Underscores Starter theme in order to work better with our custom theme going forward.</span></p>',
                'position' => 9,
                'aws_upload' => NULL,
                'created_at' => '2020-03-12 13:00:16',
                'updated_at' => '2020-06-21 01:29:50',
                'user_id' => NULL,
                'file' => NULL,
            ),
            47 => 
            array (
                'id' => 108,
                'course_id' => '1',
                'coursechapter_id' => '33',
                'title' => '{"en":"New class one"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => NULL,
                'iframe_url' => NULL,
                'video' => 'video_course_1584005261.mp4',
                'duration' => '10',
                'status' => '0',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => 'https://www.youtube.com/watch?v=ewMksAbgdBI',
                'preview_type' => 'url',
                'date_time' => NULL,
                'detail' => NULL,
                'position' => 12,
                'aws_upload' => NULL,
                'created_at' => '2020-03-12 14:56:19',
                'updated_at' => '2020-07-24 11:19:22',
                'user_id' => NULL,
                'file' => NULL,
            ),
            48 => 
            array (
                'id' => 112,
                'course_id' => '1',
                'coursechapter_id' => '33',
                'title' => '{"en":"Live class"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=71EZb94AS1k',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => NULL,
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => 'url',
                'date_time' => '2020-04-22 02:03:00',
                'detail' => NULL,
                'position' => 1,
                'aws_upload' => NULL,
                'created_at' => '2020-04-21 22:31:31',
                'updated_at' => '2020-06-11 13:03:23',
                'user_id' => NULL,
                'file' => NULL,
            ),
            49 => 
            array (
                'id' => 113,
                'course_id' => '1',
                'coursechapter_id' => '33',
                'title' => '{"en":"Live 2"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => 'https://www.youtube.com/watch?v=71EZb94AS1k',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => NULL,
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => 'url',
                'date_time' => '2020-04-30 14:40:00',
                'detail' => NULL,
                'position' => 10,
                'aws_upload' => NULL,
                'created_at' => '2020-04-21 23:57:56',
                'updated_at' => '2020-06-11 13:02:18',
                'user_id' => NULL,
                'file' => NULL,
            ),
            50 => 
            array (
                'id' => 114,
                'course_id' => '1',
                'coursechapter_id' => '33',
                'title' => '{"en":"pdf"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => '1589354252sample.pdf',
                'audio' => NULL,
                'size' => '5',
                'url' => NULL,
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => NULL,
                'status' => '1',
                'featured' => '1',
                'type' => 'pdf',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => 'url',
                'date_time' => NULL,
                'detail' => NULL,
                'position' => 11,
                'aws_upload' => NULL,
                'created_at' => '2020-05-13 12:47:32',
                'updated_at' => '2020-05-13 12:47:32',
                'user_id' => NULL,
                'file' => NULL,
            ),
            51 => 
            array (
                'id' => 115,
                'course_id' => '1',
                'coursechapter_id' => '33',
                'title' => '{"en":"Test"}',
                'image' => NULL,
                'zip' => NULL,
                'pdf' => NULL,
                'audio' => NULL,
                'size' => NULL,
                'url' => '',
                'iframe_url' => NULL,
                'video' => NULL,
                'duration' => NULL,
                'status' => '1',
                'featured' => '1',
                'type' => 'video',
                'preview_video' => NULL,
                'preview_url' => NULL,
                'preview_type' => 'url',
                'date_time' => NULL,
                'detail' => '<p>Test</p>',
                'position' => 99,
                'aws_upload' => 'https://nexthour-test.s3.ap-south-1.amazonaws.com/1596633146travel.mp4',
                'created_at' => '2020-07-28 13:49:02',
                'updated_at' => '2020-08-05 18:46:36',
                'user_id' => NULL,
                'file' => NULL,
            ),
        ));
        
        
    }
}